// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "parseSource": string;
      "parseMode": string;
      "localApiBaseURL": string;
      "localApiTimeoutMinutes": number;
      "apiEnabled": boolean;
      "apiRequireToken": boolean;
      "apiToken": string;
      "saveImages": boolean;
      "syncParseResults": boolean;
      "syncIncludeImages": boolean;
    };
  }
}
